version: '3.3'

services:
  os:
    image: mukhammad9801/mydockerrepo1:latest
    restart: always

  db:
    image: postgres    
    restart: always
    environment:
     POSTGRES_PASSWORD: secret

  java:
    image: openjdk:7
    working_dir: /home/mukhammadamin/tttt/hello.java
    

